version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://db:27017/
    depends_on:
      - db

  db:
    image: mongo:6
    ports:
      - "27017:27017"
