FROM node:20-alpine
WORKDIR /app

# SUPPRIMER = COPY node_modules ./node_modules
COPY package*.json ./
# Avoir uniquement les fichiers nécessaires pour les dépendances

RUN npm ci --omit=dev
#Sans devDependencies normalement plus rapide
# SUPPRIMER = RUN apt-get update && apt-get install -y build-essential ca-certificates locales && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen

# Copie du reste des fichiers (le code)
COPY . .

EXPOSE 3000
ENV NODE_ENV=production
# SUPPRIMER : RUN npm run build
USER root
CMD ["node", "server.js"]