# ETAPE 1 : Build
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
# Avoir uniquement les fichiers nécessaires pour les dépendances
RUN npm ci --omit=dev
#Sans devDependencies normalement plus rapide
COPY . .
# Copie du reste des fichiers (le code)

# ETAPE 2 : Execution
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app .
ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "server.js"]